#!/bin/zsh
# Runs /daily-brief headless and owns its own launchd installation.
#
#   run.sh              write today's brief now (what launchd calls)
#   run.sh --install    generate the plist and load it (8:30am, Mon-Fri)
#   run.sh --uninstall  unload and remove the plist
#
# The plist is GENERATED, never checked in: every path in it derives from this
# script's own location, so a clone anywhere installs correctly.

set -u

# Derived from the home directory name, so a clone under any account installs
# under its own label with nothing hardcoded.
LABEL="com.${HOME:t}.daily-brief"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
HOUR=8
MINUTE=30
# Weekdays only. launchd takes no weekday RANGE, so StartCalendarInterval gets an
# array of five entries -- one per day -- rather than one entry with a Weekday key.
# A manual weekend run still works; this only governs the scheduled one.
WEEKDAYS=(1 2 3 4 5)

# <repo>/.claude/skills/daily-brief/scripts/run.sh -> <repo>
SELF="${0:A}"
REPO="${BRIEFING_REPO:-${SELF:h:h:h:h:h}}"

# Logs live outside the repo: they are persistent operational output, and a
# `git clean` in the working tree should not take the run history with it.
LOG_DIR="${BRIEFING_LOG_DIR:-$HOME/Library/Logs/$LABEL}"

case "${1:-run}" in
  --install)
    mkdir -p "$HOME/Library/LaunchAgents" "$LOG_DIR"
    CAL_ENTRIES=""
    for wd in $WEEKDAYS; do
      CAL_ENTRIES+="
    <dict><key>Weekday</key><integer>$wd</integer><key>Hour</key><integer>$HOUR</integer><key>Minute</key><integer>$MINUTE</integer></dict>"
    done
    cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <!-- Generated by $SELF -- edit that script, not this file. -->
  <key>ProgramArguments</key><array><string>$SELF</string></array>
  <key>StartCalendarInterval</key>
  <array>$CAL_ENTRIES</array>
  <key>RunAtLoad</key><false/>
  <key>StandardOutPath</key><string>$LOG_DIR/launchd.out</string>
  <key>StandardErrorPath</key><string>$LOG_DIR/launchd.err</string>
  <key>ProcessType</key><string>Background</string>
</dict>
</plist>
PLIST
    plutil -lint "$PLIST" || { print -u2 "generated plist is invalid"; exit 1; }
    launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null   # idempotent reinstall
    launchctl bootstrap "gui/$(id -u)" "$PLIST" || {
      print -u2 "bootstrap failed; check: launchctl print gui/$(id -u)/$LABEL"; exit 1; }
    printf "installed %s -> %d:%02d Mon-Fri, logs in %s\n" "$LABEL" "$HOUR" "$MINUTE" "$LOG_DIR"
    exit 0
    ;;

  --uninstall)
    launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null
    rm -f "$PLIST"
    print -r -- "removed $LABEL"
    exit 0
    ;;

  run) ;;
  *) print -u2 "unknown option: $1"; exit 2 ;;
esac

# ---- the run ----

LOG="$LOG_DIR/run-$(date +%Y-%m-%d).log"
mkdir -p "$LOG_DIR"
cd "$REPO" || exit 1

# launchd gives a minimal PATH; pick up the login environment for claude, gws, qmd.
[ -f "$HOME/.zprofile" ] && source "$HOME/.zprofile"
[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc"

# Headless runs cannot answer a permission prompt, so every tool the gather needs
# must be pre-allowed. Without this the MCP-backed sections (Initiatives, You Owe,
# Slack) come back "<unavailable>" -- the tools are authenticated fine, there is
# just nobody to click approve.
#
# The default grants one prefix per MCP server the gather reads, named after the
# server keys in .mcp.json.example (`linear-server` -> `mcp__linear-server`), plus
# Slack. If your servers are named differently, or you add a source to the brief,
# override the whole list without editing this file:
#
#   BRIEFING_ALLOWED_TOOLS="mcp__linear-server mcp__slack mcp__my-server Bash Read Write Edit Glob Grep"
#
# Step 3's inbox hygiene pass is the one part of the gather that WRITES: it marks
# read and archives meeting-invite receipts (see references/inbox-hygiene.md). It
# goes through `gws` under Bash, so it needs no extra grant here -- but it does
# mean an unattended 8:30am run mutates the mailbox. Export BRIEFING_NO_MUTATE=1 to
# make the run read-only without touching the skill.
if [[ -n "${BRIEFING_ALLOWED_TOOLS:-}" ]]; then
  ALLOWED=(${=BRIEFING_ALLOWED_TOOLS})
else
  ALLOWED=(
    "mcp__linear-server"
    "mcp__slack"
    Bash Read Write Edit Glob Grep
  )
fi

{
  echo "=== start $(date -Iseconds) ==="
  claude -p "/daily-brief" --permission-mode acceptEdits --allowedTools "${ALLOWED[@]}"
  echo "=== exit $? at $(date -Iseconds) ==="
} >> "$LOG" 2>&1

find "$LOG_DIR" -name 'run-*.log' -mtime +14 -delete 2>/dev/null
exit 0
